openapi: 3.0.0
info:
  title: OpenAPI Template
  description: Template of split OpenAPI with validator
  version: 1.0.0
servers:
  - url: "http://localhost:18081/api"
    description: Local Express API
  - url: "{server}"
    description: Reverse proxy base (relative)
    variables:
      server:
        default: /api
paths:
  # 認証
  /auth/signin:
    $ref: ./paths/auth/signin/index.yml
  /auth/admin/signin:
    $ref: ./paths/auth/admin/signin/index.yml
  /auth/signout:
    $ref: ./paths/auth/signout/index.yml
  /auth/signup:
    $ref: ./paths/auth/signup/index.yml

  # ログインユーザー関連のエンドポイント
  /my/user:
    $ref: ./paths/my/user/index.yml

  # ログインユーザー関連のエンドポイント
  /items:
    $ref: ./paths/items/index.yml
  /items/{item_id}:
    $ref: ./paths/items/itemId/index.yml
  /carts:
    $ref: ./paths/carts/index.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      $ref: ./schemas/models/User.yml
    Pagenation:
      $ref: ./schemas/models/Pagination.yml
    Item:
      $ref: ./schemas/models/Item.yml
    Cart:
      $ref: ./schemas/models/Cart.yml
    ValidationError:
      $ref: ./schemas/common/ValidationError.yml
  responses:
    ValidationErrorResponse:
      $ref: ./responses/common/ValidationErrorResponse.yml

security:
  - BearerAuth: []
